require('vim._core.ui2').enable()
require("config.options")
require("pack.hooks")      -- PackChanged primero
require("pack.plugins")     -- vim.pack.add(...)
require("pack.editor.blink-cmp")
require("pack.editor.blink-pairs")
require("pack.editor.gitsigns")
require("config.treesitter")
require("config.autocmds")
require("config.keymaps")
require("config.lsp")
require("pack.ui.colorscheme")
require("pack.ui.heirline")
require("pack.ui.snack")
require("pack.ui.neotree")
require("pack.ui.whichkey")
